### ISSUE TITLE
Missing "Intake Manifold / Throttle Body"

### ISSUE THREAD

**Issue by VintB** [Ldalvik/ForzaOpenTuneFormatter#2]
Right now there's no way to add or edit Intake Manifold / Throttle Body, would it be possible to add it?

It's not an option available for all cars but some NA cars do have it.

**Comment by Ldalvik** [comment]
This is in our next update, yes. There are a few we need to add such as carburetors and restrictor plates.

**Comment by Ldalvik** [comment]
Parts are interchangeable with other existing inputs (Throttle body is just

**Comment by Ldalvik** [comment]
Didn’t mean to open and close a bunch of times. Latest update adds missing part “Restrictor Plate” (thanks @turbodoubiez)
As for the intake manifold/throttle body parts, they are actually renamed after the default ones. We’ll make it clear later on by showing what parts are the same.
